language: go

go:
 - 1.14.x

service:
 - docker

sudo: required

before_install:
    - git clone https://github.com/diodechain/cross-compile.git
    - cd cross-compile/pi-zero
    - docker image build --build-arg branch=master -t crosscompile:0.1 .
    - cd ../..

install:
  - make diode
  - make diode_race_test

before_script: make lint

script:
  - make test
  - ./diode_race_test config -list
  - ./diode_race_test time
  # test build on pi
  - docker container run crosscompile:0.1 make

env:
  - GO111MODULE=on
